apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
  labels:
    app: go-web-app
spec:
  type: NodePort
  selector:
    app: go-web-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      # nodePort: 30080   # optional: uncomment if you want a fixed NodePort
